'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './ui/nav';
import { usePathname } from 'next/navigation';
import { UserProvider } from './context/UserContext';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          pathname.includes('/dashboard') ? (<div></div>)  : <NavBar />
        }
            {children}
      </body>
    </html>
  )
}
